services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    environment:
      POSTGRES_DB: course_management
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app123
    ports:
      - "5432:5432"
